output: "{{.Dir}}/README.md"
header: |+
  [![Go Report Card](https://goreportcard.com/badge/github.com/princjef/gomarkdoc)](https://goreportcard.com/report/github.com/princjef/gomarkdoc)
  [![GitHub Actions](https://github.com/princjef/gomarkdoc/workflows/Test/badge.svg)[https://github.com/mvdan/github-actions-golang/actions?query=workflow%3ATest+branch%3Amaster]
  
