#!/bin/bash

mapName=$1
filename=$2

printf "// Code generated by gentmpl.sh; DO NOT EDIT.\n\npackage ${GOPACKAGE}\n\nvar ${mapName} = map[string]string{\n" > "${filename}.go"

for f in ./templates/*.gotxt
do
	f=${f##*/}
	name=${f%.*}
	printf "\t\"$name\": \`" >> "${filename}.go"
	cat ./templates/$f >> "${filename}.go"
	printf "\`,\n" >> "${filename}.go"
done

printf "}\n" >> "${filename}.go"

gofmt -s -w "${filename}.go"
