package gomarkdoc

// Code generated by gentmpl.sh. DO NOT EDIT.

var templates = map[string]string{
	"doc": `{{- range .Blocks -}}
	{{- if eq .Kind "paragraph" -}}
		{{- paragraph .Text -}}
	{{- else if eq .Kind "code" -}}
		{{- codeBlock "" .Text -}}
	{{- else if eq .Kind "header" -}}
		{{- header .Level .Text -}}
	{{- end -}}
{{- end -}}`,
	"example": `{{- accordionHeader .Title -}}

{{- template "doc" .Doc -}}

{{- codeBlock "go" .Code -}}

{{- accordionTerminator -}}`,
	"file": `<!-- Code generated by gomarkdoc. DO NOT EDIT -->

{{.Header -}}

{{- range .Packages -}}
	{{- template "package" . -}}
{{- end -}}

{{- .Footer}}

Generated by {{link "gomarkdoc" "https://github.com/princjef/gomarkdoc"}}`,
	"func": `{{- header .Level .Title -}}

{{- codeBlock "go" .Signature -}}

{{- template "doc" .Doc -}}

{{- range .Examples -}}
	{{- template "example" . -}}
{{- end -}}`,
	"index": `{{- if len .Consts -}}

	{{- localHref "Constants" | link "Constants" | listEntry 0 -}}
	
{{- end -}}

{{- if len .Vars -}}

	{{- localHref "Variables" | link "Variables" | listEntry 0 -}}

{{- end -}}

{{- range .Funcs -}}

	{{- localHref .Title | link .Signature | listEntry 0 -}}

{{- end -}}

{{- range .Types -}}

	{{- localHref .Title | link .Title | listEntry 0 -}}

	{{- range .Funcs -}}
		{{- localHref .Title | link .Signature | listEntry 1 -}}
	{{- end -}}

	{{- range .Methods -}}
		{{- localHref .Title | link .Signature | listEntry 1 -}}
	{{- end -}}

{{- end -}}

{{- spacer -}}`,
	"package": `{{- if eq .Name "main" -}}
	{{- header .Level .Dirname -}}
{{- else -}}
	{{- header .Level .Name -}}
{{- end -}}

{{- codeBlock "go" .Import -}}

{{- template "doc" .Doc -}}

{{- range .Examples -}}
	{{- template "example" . -}}
{{- end -}}

{{- header (add .Level 1) "Index" -}}

{{- template "index" . -}}

{{- if len .Consts -}}

	{{- header (add .Level 1) "Constants" -}}

	{{- range .Consts -}}
		{{- template "value" . -}}
	{{- end -}}

{{- end -}}

{{- if len .Vars -}}

	{{- header (add .Level 1) "Variables" -}}

	{{- range .Vars -}}
		{{- template "value" . -}}
	{{- end -}}

{{- end -}}

{{- range .Funcs -}}
	{{- template "func" . -}}
{{- end -}}

{{- range .Types -}}
	{{- template "type" . -}}
{{- end -}}`,
	"type": `{{- header .Level .Title -}}

{{- template "doc" .Doc -}}

{{- codeBlock "go" .Decl -}}

{{- range .Examples -}}
	{{- template "example" . -}}
{{- end -}}

{{- range .Funcs -}}
	{{- template "func" . -}}
{{- end -}}

{{- range .Methods -}}
	{{- template "func" . -}}
{{- end -}}`,
	"value": `{{- template "doc" .Doc -}}

{{- codeBlock "go" .Decl -}}`,
}
